### ISSUE TITLE
Status of Project

### ISSUE THREAD

**Issue by rhclayto** [80prozent/FaceShiftC4D#3]
Hi,

I know this project is a few years old, & FaceShift is not being sold anymore, but I have a few questions about this plugin:

1) What is the highest version of Faceshift it will work with?
2) What is the highest version of Cinema 4D it will work with?
3) Is the version available here on GitHub the most up-to-date version, or has it been updated elsewhere? I saw on a Vimeo page that the video's author had obtained a newer version of this plugin directly from the developer ( https://vimeo.com/70897075 ).

**Comment by 80prozent** [comment]
Hey
ye. right, the sources here are not up to date.

You can download the latest version here:
http://www.differentdesign.de/downloads/FaceShiftC4d.zip

to your questions:
1. It should work with all faceshift versions.
2. I think i tested r13-r15. Its plain python, so hopefully it will work in r16/r17/r18 the same.
3. answered above ;)

Let me know if you need more help to get it to run for you.

Cheers

**Comment by rhclayto** [comment]
Thank you, that answers all of my questions. Also thank you for the link to the latest version. I am on r15 now so this should work well. I will try it in r18 when I have it & add a note here how it worked for me.

Grüße
